/**
 * OpenApi specification - Mauro
 * OpenApi documentation for Spring Security
 *
 * The version of the OpenAPI document: 1.0
 * Contact: maurocristovao1998@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Book from './Book';
import User from './User';

/**
 * The BookTransactionHistory model module.
 * @module model/BookTransactionHistory
 * @version 1.0
 */
class BookTransactionHistory {
    /**
     * Constructs a new <code>BookTransactionHistory</code>.
     * @alias module:model/BookTransactionHistory
     */
    constructor() { 
        
        BookTransactionHistory.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BookTransactionHistory</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BookTransactionHistory} obj Optional instance to populate.
     * @return {module:model/BookTransactionHistory} The populated <code>BookTransactionHistory</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BookTransactionHistory();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('createdDate')) {
                obj['createdDate'] = ApiClient.convertToType(data['createdDate'], 'Date');
            }
            if (data.hasOwnProperty('lastModifiedDate')) {
                obj['lastModifiedDate'] = ApiClient.convertToType(data['lastModifiedDate'], 'Date');
            }
            if (data.hasOwnProperty('createdBy')) {
                obj['createdBy'] = ApiClient.convertToType(data['createdBy'], 'Number');
            }
            if (data.hasOwnProperty('lastModifiedBy')) {
                obj['lastModifiedBy'] = ApiClient.convertToType(data['lastModifiedBy'], 'Number');
            }
            if (data.hasOwnProperty('user')) {
                obj['user'] = User.constructFromObject(data['user']);
            }
            if (data.hasOwnProperty('book')) {
                obj['book'] = Book.constructFromObject(data['book']);
            }
            if (data.hasOwnProperty('returned')) {
                obj['returned'] = ApiClient.convertToType(data['returned'], 'Boolean');
            }
            if (data.hasOwnProperty('returnApproved')) {
                obj['returnApproved'] = ApiClient.convertToType(data['returnApproved'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BookTransactionHistory</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BookTransactionHistory</code>.
     */
    static validateJSON(data) {
        // validate the optional field `user`
        if (data['user']) { // data not null
          User.validateJSON(data['user']);
        }
        // validate the optional field `book`
        if (data['book']) { // data not null
          Book.validateJSON(data['book']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
BookTransactionHistory.prototype['id'] = undefined;

/**
 * @member {Date} createdDate
 */
BookTransactionHistory.prototype['createdDate'] = undefined;

/**
 * @member {Date} lastModifiedDate
 */
BookTransactionHistory.prototype['lastModifiedDate'] = undefined;

/**
 * @member {Number} createdBy
 */
BookTransactionHistory.prototype['createdBy'] = undefined;

/**
 * @member {Number} lastModifiedBy
 */
BookTransactionHistory.prototype['lastModifiedBy'] = undefined;

/**
 * @member {module:model/User} user
 */
BookTransactionHistory.prototype['user'] = undefined;

/**
 * @member {module:model/Book} book
 */
BookTransactionHistory.prototype['book'] = undefined;

/**
 * @member {Boolean} returned
 */
BookTransactionHistory.prototype['returned'] = undefined;

/**
 * @member {Boolean} returnApproved
 */
BookTransactionHistory.prototype['returnApproved'] = undefined;






export default BookTransactionHistory;

