/**
 * OpenApi specification - Mauro
 * OpenApi documentation for Spring Security
 *
 * The version of the OpenAPI document: 1.0
 * Contact: maurocristovao1998@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Book from './Book';

/**
 * The Feedback model module.
 * @module model/Feedback
 * @version 1.0
 */
class Feedback {
    /**
     * Constructs a new <code>Feedback</code>.
     * @alias module:model/Feedback
     * @param note {Number} 
     * @param comment {String} 
     * @param book {module:model/Book} 
     */
    constructor(note, comment, book) { 
        
        Feedback.initialize(this, note, comment, book);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, note, comment, book) { 
        obj['note'] = note;
        obj['comment'] = comment;
        obj['book'] = book;
    }

    /**
     * Constructs a <code>Feedback</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Feedback} obj Optional instance to populate.
     * @return {module:model/Feedback} The populated <code>Feedback</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Feedback();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('createdDate')) {
                obj['createdDate'] = ApiClient.convertToType(data['createdDate'], 'Date');
            }
            if (data.hasOwnProperty('lastModifiedDate')) {
                obj['lastModifiedDate'] = ApiClient.convertToType(data['lastModifiedDate'], 'Date');
            }
            if (data.hasOwnProperty('createdBy')) {
                obj['createdBy'] = ApiClient.convertToType(data['createdBy'], 'Number');
            }
            if (data.hasOwnProperty('lastModifiedBy')) {
                obj['lastModifiedBy'] = ApiClient.convertToType(data['lastModifiedBy'], 'Number');
            }
            if (data.hasOwnProperty('note')) {
                obj['note'] = ApiClient.convertToType(data['note'], 'Number');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
            if (data.hasOwnProperty('book')) {
                obj['book'] = Book.constructFromObject(data['book']);
            }
            if (data.hasOwnProperty('ownFeedback')) {
                obj['ownFeedback'] = ApiClient.convertToType(data['ownFeedback'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Feedback</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Feedback</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Feedback.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['comment'] && !(typeof data['comment'] === 'string' || data['comment'] instanceof String)) {
            throw new Error("Expected the field `comment` to be a primitive type in the JSON string but got " + data['comment']);
        }
        // validate the optional field `book`
        if (data['book']) { // data not null
          Book.validateJSON(data['book']);
        }

        return true;
    }


}

Feedback.RequiredProperties = ["note", "comment", "book"];

/**
 * @member {Number} id
 */
Feedback.prototype['id'] = undefined;

/**
 * @member {Date} createdDate
 */
Feedback.prototype['createdDate'] = undefined;

/**
 * @member {Date} lastModifiedDate
 */
Feedback.prototype['lastModifiedDate'] = undefined;

/**
 * @member {Number} createdBy
 */
Feedback.prototype['createdBy'] = undefined;

/**
 * @member {Number} lastModifiedBy
 */
Feedback.prototype['lastModifiedBy'] = undefined;

/**
 * @member {Number} note
 */
Feedback.prototype['note'] = undefined;

/**
 * @member {String} comment
 */
Feedback.prototype['comment'] = undefined;

/**
 * @member {module:model/Book} book
 */
Feedback.prototype['book'] = undefined;

/**
 * @member {Boolean} ownFeedback
 */
Feedback.prototype['ownFeedback'] = undefined;






export default Feedback;

