/**
 * OpenApi specification - Mauro
 * OpenApi documentation for Spring Security
 *
 * The version of the OpenAPI document: 1.0
 * Contact: maurocristovao1998@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BookResponseDto from './BookResponseDto';

/**
 * The PageResponseBookResponseDto model module.
 * @module model/PageResponseBookResponseDto
 * @version 1.0
 */
class PageResponseBookResponseDto {
    /**
     * Constructs a new <code>PageResponseBookResponseDto</code>.
     * @alias module:model/PageResponseBookResponseDto
     */
    constructor() { 
        
        PageResponseBookResponseDto.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PageResponseBookResponseDto</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PageResponseBookResponseDto} obj Optional instance to populate.
     * @return {module:model/PageResponseBookResponseDto} The populated <code>PageResponseBookResponseDto</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PageResponseBookResponseDto();

            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], [BookResponseDto]);
            }
            if (data.hasOwnProperty('number')) {
                obj['number'] = ApiClient.convertToType(data['number'], 'Number');
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('totalElements')) {
                obj['totalElements'] = ApiClient.convertToType(data['totalElements'], 'Number');
            }
            if (data.hasOwnProperty('totalPages')) {
                obj['totalPages'] = ApiClient.convertToType(data['totalPages'], 'Number');
            }
            if (data.hasOwnProperty('first')) {
                obj['first'] = ApiClient.convertToType(data['first'], 'Boolean');
            }
            if (data.hasOwnProperty('last')) {
                obj['last'] = ApiClient.convertToType(data['last'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PageResponseBookResponseDto</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PageResponseBookResponseDto</code>.
     */
    static validateJSON(data) {
        if (data['content']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['content'])) {
                throw new Error("Expected the field `content` to be an array in the JSON data but got " + data['content']);
            }
            // validate the optional field `content` (array)
            for (const item of data['content']) {
                BookResponseDto.validateJSON(item);
            };
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/BookResponseDto>} content
 */
PageResponseBookResponseDto.prototype['content'] = undefined;

/**
 * @member {Number} number
 */
PageResponseBookResponseDto.prototype['number'] = undefined;

/**
 * @member {Number} size
 */
PageResponseBookResponseDto.prototype['size'] = undefined;

/**
 * @member {Number} totalElements
 */
PageResponseBookResponseDto.prototype['totalElements'] = undefined;

/**
 * @member {Number} totalPages
 */
PageResponseBookResponseDto.prototype['totalPages'] = undefined;

/**
 * @member {Boolean} first
 */
PageResponseBookResponseDto.prototype['first'] = undefined;

/**
 * @member {Boolean} last
 */
PageResponseBookResponseDto.prototype['last'] = undefined;






export default PageResponseBookResponseDto;

