/**
 * OpenApi specification - Mauro
 * OpenApi documentation for Spring Security
 *
 * The version of the OpenAPI document: 1.0
 * Contact: maurocristovao1998@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Book from './Book';
import BookTransactionHistory from './BookTransactionHistory';
import GrantedAuthority from './GrantedAuthority';
import Role from './Role';

/**
 * The User model module.
 * @module model/User
 * @version 1.0
 */
class User {
    /**
     * Constructs a new <code>User</code>.
     * @alias module:model/User
     */
    constructor() { 
        
        User.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/User} obj Optional instance to populate.
     * @return {module:model/User} The populated <code>User</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new User();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('firstname')) {
                obj['firstname'] = ApiClient.convertToType(data['firstname'], 'String');
            }
            if (data.hasOwnProperty('lastname')) {
                obj['lastname'] = ApiClient.convertToType(data['lastname'], 'String');
            }
            if (data.hasOwnProperty('birthdate')) {
                obj['birthdate'] = ApiClient.convertToType(data['birthdate'], 'Date');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('accountLocked')) {
                obj['accountLocked'] = ApiClient.convertToType(data['accountLocked'], 'Boolean');
            }
            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('roles')) {
                obj['roles'] = ApiClient.convertToType(data['roles'], [Role]);
            }
            if (data.hasOwnProperty('books')) {
                obj['books'] = ApiClient.convertToType(data['books'], [Book]);
            }
            if (data.hasOwnProperty('histories')) {
                obj['histories'] = ApiClient.convertToType(data['histories'], [BookTransactionHistory]);
            }
            if (data.hasOwnProperty('createdDate')) {
                obj['createdDate'] = ApiClient.convertToType(data['createdDate'], 'Date');
            }
            if (data.hasOwnProperty('updatedDate')) {
                obj['updatedDate'] = ApiClient.convertToType(data['updatedDate'], 'Date');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('authorities')) {
                obj['authorities'] = ApiClient.convertToType(data['authorities'], [GrantedAuthority]);
            }
            if (data.hasOwnProperty('fullname')) {
                obj['fullname'] = ApiClient.convertToType(data['fullname'], 'String');
            }
            if (data.hasOwnProperty('credentialsNonExpired')) {
                obj['credentialsNonExpired'] = ApiClient.convertToType(data['credentialsNonExpired'], 'Boolean');
            }
            if (data.hasOwnProperty('accountNonExpired')) {
                obj['accountNonExpired'] = ApiClient.convertToType(data['accountNonExpired'], 'Boolean');
            }
            if (data.hasOwnProperty('accountNonLocked')) {
                obj['accountNonLocked'] = ApiClient.convertToType(data['accountNonLocked'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>User</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>User</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['firstname'] && !(typeof data['firstname'] === 'string' || data['firstname'] instanceof String)) {
            throw new Error("Expected the field `firstname` to be a primitive type in the JSON string but got " + data['firstname']);
        }
        // ensure the json data is a string
        if (data['lastname'] && !(typeof data['lastname'] === 'string' || data['lastname'] instanceof String)) {
            throw new Error("Expected the field `lastname` to be a primitive type in the JSON string but got " + data['lastname']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }
        if (data['roles']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['roles'])) {
                throw new Error("Expected the field `roles` to be an array in the JSON data but got " + data['roles']);
            }
            // validate the optional field `roles` (array)
            for (const item of data['roles']) {
                Role.validateJSON(item);
            };
        }
        if (data['books']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['books'])) {
                throw new Error("Expected the field `books` to be an array in the JSON data but got " + data['books']);
            }
            // validate the optional field `books` (array)
            for (const item of data['books']) {
                Book.validateJSON(item);
            };
        }
        if (data['histories']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['histories'])) {
                throw new Error("Expected the field `histories` to be an array in the JSON data but got " + data['histories']);
            }
            // validate the optional field `histories` (array)
            for (const item of data['histories']) {
                BookTransactionHistory.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        if (data['authorities']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['authorities'])) {
                throw new Error("Expected the field `authorities` to be an array in the JSON data but got " + data['authorities']);
            }
            // validate the optional field `authorities` (array)
            for (const item of data['authorities']) {
                GrantedAuthority.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['fullname'] && !(typeof data['fullname'] === 'string' || data['fullname'] instanceof String)) {
            throw new Error("Expected the field `fullname` to be a primitive type in the JSON string but got " + data['fullname']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
User.prototype['id'] = undefined;

/**
 * @member {String} firstname
 */
User.prototype['firstname'] = undefined;

/**
 * @member {String} lastname
 */
User.prototype['lastname'] = undefined;

/**
 * @member {Date} birthdate
 */
User.prototype['birthdate'] = undefined;

/**
 * @member {String} email
 */
User.prototype['email'] = undefined;

/**
 * @member {String} password
 */
User.prototype['password'] = undefined;

/**
 * @member {Boolean} accountLocked
 */
User.prototype['accountLocked'] = undefined;

/**
 * @member {Boolean} enabled
 */
User.prototype['enabled'] = undefined;

/**
 * @member {Array.<module:model/Role>} roles
 */
User.prototype['roles'] = undefined;

/**
 * @member {Array.<module:model/Book>} books
 */
User.prototype['books'] = undefined;

/**
 * @member {Array.<module:model/BookTransactionHistory>} histories
 */
User.prototype['histories'] = undefined;

/**
 * @member {Date} createdDate
 */
User.prototype['createdDate'] = undefined;

/**
 * @member {Date} updatedDate
 */
User.prototype['updatedDate'] = undefined;

/**
 * @member {String} name
 */
User.prototype['name'] = undefined;

/**
 * @member {String} username
 */
User.prototype['username'] = undefined;

/**
 * @member {Array.<module:model/GrantedAuthority>} authorities
 */
User.prototype['authorities'] = undefined;

/**
 * @member {String} fullname
 */
User.prototype['fullname'] = undefined;

/**
 * @member {Boolean} credentialsNonExpired
 */
User.prototype['credentialsNonExpired'] = undefined;

/**
 * @member {Boolean} accountNonExpired
 */
User.prototype['accountNonExpired'] = undefined;

/**
 * @member {Boolean} accountNonLocked
 */
User.prototype['accountNonLocked'] = undefined;






export default User;

