/**
 * OpenApi specification - Mauro
 * OpenApi documentation for Spring Security
 *
 * The version of the OpenAPI document: 1.0
 * Contact: maurocristovao1998@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Feedback from '../model/Feedback';
import PageResponseFeedback from '../model/PageResponseFeedback';

/**
* Feedback service.
* @module api/FeedbackApi
* @version 1.0
*/
export default class FeedbackApi {

    /**
    * Constructs a new FeedbackApi. 
    * @alias module:api/FeedbackApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the findAllByBook operation.
     * @callback module:api/FeedbackApi~findAllByBookCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PageResponseFeedback} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} bookId 
     * @param {Object} opts Optional parameters
     * @param {Number} [page = 0)] 
     * @param {Number} [size = 20)] 
     * @param {module:api/FeedbackApi~findAllByBookCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PageResponseFeedback}
     */
    findAllByBook(bookId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'bookId' is set
      if (bookId === undefined || bookId === null) {
        throw new Error("Missing the required parameter 'bookId' when calling findAllByBook");
      }

      let pathParams = {
        'bookId': bookId
      };
      let queryParams = {
        'page': opts['page'],
        'size': opts['size']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = [];
      let accepts = ['*/*'];
      let returnType = PageResponseFeedback;
      return this.apiClient.callApi(
        '/feedbacks/book/{bookId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the save operation.
     * @callback module:api/FeedbackApi~saveCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Feedback} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/Feedback} feedback 
     * @param {module:api/FeedbackApi~saveCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Feedback}
     */
    save(feedback, callback) {
      let postBody = feedback;
      // verify the required parameter 'feedback' is set
      if (feedback === undefined || feedback === null) {
        throw new Error("Missing the required parameter 'feedback' when calling save");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['*/*'];
      let returnType = Feedback;
      return this.apiClient.callApi(
        '/feedbacks', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
